// <auto-generated />
using System;
using BookLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BookLibraryDbContext))]
    [Migration("20250703143714_AddMoreBooksAndGenres")]
    partial class AddMoreBooksAndGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookLibrary.Auth.Model.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "George Orwell",
                            Description = "Dystopian novel",
                            GenreId = 1,
                            ISBN = "978-0452284234",
                            PublicationYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R. Tolkien",
                            Description = "Fantasy adventure",
                            GenreId = 4,
                            ISBN = "978-0547928227",
                            PublicationYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Stephen Hawking",
                            Description = "Cosmology explained for the general public",
                            GenreId = 2,
                            ISBN = "978-0553380163",
                            PublicationYear = 1988,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Andy Weir",
                            Description = "Survival on Mars",
                            GenreId = 3,
                            ISBN = "978-0553418026",
                            PublicationYear = 2011,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Dan Brown",
                            Description = "Mystery thriller novel",
                            GenreId = 5,
                            ISBN = "978-0307474278",
                            PublicationYear = 2003,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Harper Lee",
                            Description = "Classic of modern American literature",
                            GenreId = 1,
                            ISBN = "978-0060935467",
                            PublicationYear = 1960,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Yuval Noah Harari",
                            Description = "History of humankind",
                            GenreId = 2,
                            ISBN = "978-0062316097",
                            PublicationYear = 2011,
                            Title = "Sapiens: A Brief History of Humankind"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Frank Herbert",
                            Description = "Epic science fiction novel",
                            GenreId = 3,
                            ISBN = "978-0441172719",
                            PublicationYear = 1965,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.K. Rowling",
                            Description = "First book in the Harry Potter series",
                            GenreId = 4,
                            ISBN = "978-0590353427",
                            PublicationYear = 1997,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Gillian Flynn",
                            Description = "Psychological thriller and mystery",
                            GenreId = 5,
                            ISBN = "978-0307588371",
                            PublicationYear = 2012,
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Walter Isaacson",
                            Description = "Biography of Steve Jobs",
                            GenreId = 6,
                            ISBN = "978-1451648539",
                            PublicationYear = 2011,
                            Title = "Steve Jobs"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Anne Frank",
                            Description = "Diary of Anne Frank during WWII",
                            GenreId = 7,
                            ISBN = "978-0553296983",
                            PublicationYear = 1947,
                            Title = "The Diary of a Young Girl"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Stephen King",
                            Description = "Horror novel about a shapeshifting entity",
                            GenreId = 8,
                            ISBN = "978-1501142970",
                            PublicationYear = 1986,
                            Title = "It"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Jane Austen",
                            Description = "Classic romance novel",
                            GenreId = 9,
                            ISBN = "978-1503290563",
                            PublicationYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Stephen R. Covey",
                            Description = "Self-help classic",
                            GenreId = 10,
                            ISBN = "978-0743269513",
                            PublicationYear = 1989,
                            Title = "The 7 Habits of Highly Effective People"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Aldous Huxley",
                            Description = "Dystopian science fiction",
                            GenreId = 1,
                            ISBN = "978-0060850524",
                            PublicationYear = 1932,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Tara Westover",
                            Description = "Memoir of a woman who leaves her survivalist family",
                            GenreId = 6,
                            ISBN = "978-0399590504",
                            PublicationYear = 2018,
                            Title = "Educated"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Barbara W. Tuchman",
                            Description = "History of the start of WWI",
                            GenreId = 7,
                            ISBN = "978-0345476098",
                            PublicationYear = 1962,
                            Title = "The Guns of August"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Bram Stoker",
                            Description = "Classic horror novel",
                            GenreId = 8,
                            ISBN = "978-0486411095",
                            PublicationYear = 1897,
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Jojo Moyes",
                            Description = "Romantic drama novel",
                            GenreId = 9,
                            ISBN = "978-0143124542",
                            PublicationYear = 2012,
                            Title = "Me Before You"
                        },
                        new
                        {
                            Id = 21,
                            Author = "James Clear",
                            Description = "Guide to building good habits",
                            GenreId = 10,
                            ISBN = "978-0735211292",
                            PublicationYear = 2018,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 22,
                            Author = "George Orwell",
                            Description = "Political satire",
                            GenreId = 1,
                            ISBN = "978-0451526342",
                            PublicationYear = 1945,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Michelle Obama",
                            Description = "Memoir of the former First Lady",
                            GenreId = 6,
                            ISBN = "978-1524763138",
                            PublicationYear = 2018,
                            Title = "Becoming"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Mary Beard",
                            Description = "History of Rome",
                            GenreId = 7,
                            ISBN = "978-1631492228",
                            PublicationYear = 2015,
                            Title = "SPQR: A History of Ancient Rome"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Stephen King",
                            Description = "Horror at a haunted hotel",
                            GenreId = 8,
                            ISBN = "978-0307743657",
                            PublicationYear = 1977,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Nicholas Sparks",
                            Description = "Romantic drama",
                            GenreId = 9,
                            ISBN = "978-0446605236",
                            PublicationYear = 1996,
                            Title = "The Notebook"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Viktor E. Frankl",
                            Description = "Psychological memoir",
                            GenreId = 10,
                            ISBN = "978-0807014295",
                            PublicationYear = 1946,
                            Title = "Man's Search for Meaning"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Ray Bradbury",
                            Description = "Dystopian novel about book burning",
                            GenreId = 1,
                            ISBN = "978-1451673319",
                            PublicationYear = 1953,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Nelson Mandela",
                            Description = "Autobiography of Nelson Mandela",
                            GenreId = 6,
                            ISBN = "978-0316548182",
                            PublicationYear = 1994,
                            Title = "Long Walk to Freedom"
                        },
                        new
                        {
                            Id = 30,
                            Author = "David McCullough",
                            Description = "Biography of the Wright brothers",
                            GenreId = 7,
                            ISBN = "978-1476728759",
                            PublicationYear = 2015,
                            Title = "The Wright Brothers"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Shirley Jackson",
                            Description = "Classic haunted house horror",
                            GenreId = 8,
                            ISBN = "978-0143039983",
                            PublicationYear = 1959,
                            Title = "The Haunting of Hill House"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Diana Gabaldon",
                            Description = "Time-travel romance",
                            GenreId = 9,
                            ISBN = "978-0440212560",
                            PublicationYear = 1991,
                            Title = "Outlander"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Eckhart Tolle",
                            Description = "Spiritual self-help book",
                            GenreId = 10,
                            ISBN = "978-1577314806",
                            PublicationYear = 1997,
                            Title = "The Power of Now"
                        },
                        new
                        {
                            Id = 34,
                            Author = "William Golding",
                            Description = "Novel about boys stranded on an island",
                            GenreId = 1,
                            ISBN = "978-0399501487",
                            PublicationYear = 1954,
                            Title = "Lord of the Flies"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Ron Chernow",
                            Description = "Biography of Alexander Hamilton",
                            GenreId = 6,
                            ISBN = "978-0143034759",
                            PublicationYear = 2004,
                            Title = "Alexander Hamilton"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Doris Kearns Goodwin",
                            Description = "History of Abraham Lincoln's cabinet",
                            GenreId = 7,
                            ISBN = "978-0743270755",
                            PublicationYear = 2005,
                            Title = "Team of Rivals"
                        },
                        new
                        {
                            Id = 37,
                            Author = "William Peter Blatty",
                            Description = "Horror novel about demonic possession",
                            GenreId = 8,
                            ISBN = "978-0061007224",
                            PublicationYear = 1971,
                            Title = "The Exorcist"
                        },
                        new
                        {
                            Id = 38,
                            Author = "John Green",
                            Description = "Young adult romance",
                            GenreId = 9,
                            ISBN = "978-0142424179",
                            PublicationYear = 2012,
                            Title = "The Fault in Our Stars"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Carol S. Dweck",
                            Description = "Self-help on growth mindset",
                            GenreId = 10,
                            ISBN = "978-0345472328",
                            PublicationYear = 2006,
                            Title = "Mindset: The New Psychology of Success"
                        },
                        new
                        {
                            Id = 40,
                            Author = "J.D. Salinger",
                            Description = "Classic coming-of-age novel",
                            GenreId = 1,
                            ISBN = "978-0316769488",
                            PublicationYear = 1951,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Walter Isaacson",
                            Description = "Biography of Albert Einstein",
                            GenreId = 6,
                            ISBN = "978-0743264730",
                            PublicationYear = 2007,
                            Title = "Einstein: His Life and Universe"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Jared Diamond",
                            Description = "History of societies",
                            GenreId = 7,
                            ISBN = "978-0393317558",
                            PublicationYear = 1997,
                            Title = "Guns, Germs, and Steel"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Stephen King",
                            Description = "Horror about a cursed burial ground",
                            GenreId = 8,
                            ISBN = "978-1501156700",
                            PublicationYear = 1983,
                            Title = "Pet Sematary"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Jasmine Guillory",
                            Description = "Contemporary romance",
                            GenreId = 9,
                            ISBN = "978-0399587665",
                            PublicationYear = 2018,
                            Title = "The Wedding Date"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Mark Manson",
                            Description = "Self-help on living a good life",
                            GenreId = 10,
                            ISBN = "978-0062457714",
                            PublicationYear = 2016,
                            Title = "The Subtle Art of Not Giving a F*ck"
                        },
                        new
                        {
                            Id = 46,
                            Author = "F. Scott Fitzgerald",
                            Description = "Classic American novel",
                            GenreId = 1,
                            ISBN = "978-0743273565",
                            PublicationYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Laura Hillenbrand",
                            Description = "Biography of a WWII hero",
                            GenreId = 6,
                            ISBN = "978-0812974492",
                            PublicationYear = 2010,
                            Title = "Unbroken"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Rebecca Skloot",
                            Description = "Biography and science history",
                            GenreId = 7,
                            ISBN = "978-1400052189",
                            PublicationYear = 2010,
                            Title = "The Immortal Life of Henrietta Lacks"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Josh Malerman",
                            Description = "Post-apocalyptic horror",
                            GenreId = 8,
                            ISBN = "978-0062259653",
                            PublicationYear = 2014,
                            Title = "Bird Box"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Casey McQuiston",
                            Description = "Romantic comedy novel",
                            GenreId = 9,
                            ISBN = "978-1250316776",
                            PublicationYear = 2019,
                            Title = "Red, White & Royal Blue"
                        });
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fictional stories and novels",
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Real stories and informational books",
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Science fiction and futuristic stories",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fantasy and magical stories",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Mystery and detective stories",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Life stories of notable people",
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Books about historical events and people",
                            Name = "History"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Scary and supernatural stories",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Love stories and romantic novels",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Books for personal development",
                            Name = "Self-Help"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Book", b =>
                {
                    b.HasOne("BookLibrary.Data.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BookLibrary.Auth.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BookLibrary.Auth.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibrary.Auth.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BookLibrary.Auth.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookLibrary.Data.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
